# Generated by Django 2.1.2 on 2018-11-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181102_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmanager',
            name='locationID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Clinic'),
            preserve_default=False,
        ),
    ]
