# Generated by Django 2.1.2 on 2018-11-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181104_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='deliveredDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
